# Generated by Django 3.2.8 on 2021-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='back_money',
            field=models.IntegerField(default=5058697471048833),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='national_code',
            field=models.IntegerField(default=1000000000),
        ),
    ]
