# Generated by Django 3.2.8 on 2021-10-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211023_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='media/user/'),
        ),
    ]
