# Generated by Django 3.2.8 on 2021-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211025_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='firla',
            field=models.CharField(default='', max_length=20),
        ),
    ]
