# Generated by Django 3.2.8 on 2021-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userinfo_firla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='back_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national_code',
            field=models.IntegerField(),
        ),
    ]
