# Generated by Django 3.2.8 on 2021-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211125_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='back_money',
            field=models.IntegerField(default=0),
        ),
    ]
