# Generated by Django 3.2.8 on 2021-10-23 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Shop Store'), (2, 'Post'), (3, 'Delivered')], default=1)),
                ('payment', models.SmallIntegerField(choices=[(1, 'Cash'), (1, 'Cash On Delivery')], default=1)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
